site_name: LSEN691_TD_QGIS
site_url: ""
use_directory_urls: false
plugins: []
theme:
  name: readthedocs
nav:
  - Introduction: index.md
  - Préparation: preparation.md
  - Prise en main: prise_en_main.md
  - Classification: classification.md
  - Surface: surface.md