site_name: "UVSQ_LSEN691_TD_QGIS"
site_url: "https://nicoudart.github.io/UVSQ_LSEN691_TD_QGIS"
site_author: "Nicolas OUDART"

theme:
  name: readthedocs
nav:
  - Introduction: index.md
  - Préparation: preparation.md
  - Prise en main: prise_en_main.md
  - Classification: classification.md
  - Surface: surface.md